
default_platform(:android)

platform :android do
  desc "Lane for Android Firebase app distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
    app: "1:4198372643:android:18df269c4c17ab388d6896",
    firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
    ipa_path: "build/app/outputs/flutter-apk/app-production-release.apk",
    android_artifact_type: "APK",
    android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
    testers: "hassan.shbib@mail.ru",
    release_notes: "Production release"
  )
  end
end
